import type { Book } from "./types";

const mockBooks: Book[] = [
  {
    id: "1",
    slug: "neuromancer",
    title: "Neuromancer",
    author: "William Gibson",
    source: "Project Gutenberg",
    progress: 65,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-28",
    genre: "Cyberpunk",
    chapters: [
      { title: "Chiba City Blues", read: true },
      { title: "The Shopping Expedition", read: true },
      { title: "The Straylight Run", read: false },
    ],
    content: "The sky above the port was the color of television, tuned to a dead channel...",
  },
  {
    id: "2",
    slug: "do-androids-dream-of-electric-sheep",
    title: "Do Androids Dream of Electric Sheep?",
    author: "Philip K. Dick",
    source: "Standard Ebooks",
    progress: 33,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-27",
    genre: "Sci-Fi",
    chapters: [{ title: "Chapter 1", read: true }, { title: "Chapter 2", read: false }],
    content: "A mercury-arc C-plus unit jibbered away in a corner of the bedroom...",
  },
  {
    id: "3",
    slug: "snow-crash",
    title: "Snow Crash",
    author: "Neal Stephenson",
    source: "Custom URL",
    progress: 80,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-29",
    genre: "Cyberpunk",
    chapters: [{ title: "Part I", read: true }, { title: "Part II", read: true }],
    content: "The Deliverator belongs to an elite order, a hallowed sub-category...",
  },
  {
    id: "4",
    slug: "foundation",
    title: "Foundation",
    author: "Isaac Asimov",
    source: "Project Gutenberg",
    progress: 15,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-25",
    genre: "Sci-Fi",
    chapters: [{ title: "The Psychohistorians", read: false }],
    content: "Hari Seldon — ...born in the 11,988th year of the Galactic Era...",
  },
  {
    id: "5",
    slug: "hyperion",
    title: "Hyperion",
    author: "Dan Simmons",
    source: "Standard Ebooks",
    progress: 95,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-29",
    genre: "Sci-Fi Opera",
    chapters: [{ title: "The Priest's Tale", read: true }, { title: "The Soldier's Tale", read: true }],
    content: "On the world called Hyperion, beyond the law of the Hegemony of Man, there waits the creature called the Shrike.",
  },
  {
    id: "6",
    slug: "a-scanner-darkly",
    title: "A Scanner Darkly",
    author: "Philip K. Dick",
    source: "Standard Ebooks",
    progress: 5,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-30",
    genre: "Sci-Fi",
    chapters: [{ title: "Chapter 1", read: false }],
    content: "Once a guy stood all day shaking bugs from his hair.",
  },
  {
    id: "7",
    slug: "the-hitchhikers-guide-to-the-galaxy",
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    source: "Custom URL",
    progress: 42,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-28",
    genre: "Comedy Sci-Fi",
    chapters: [{ title: "Chapter 1", read: true }, { title: "Chapter 2", read: true }],
    content: "Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun.",
  },
  {
    id: "8",
    slug: "dune",
    title: "Dune",
    author: "Frank Herbert",
    source: "Project Gutenberg",
    progress: 0,
    coverUrl: "https://placehold.co/600x800",
    lastAccessed: "2024-07-30",
    genre: "Sci-Fi",
    chapters: [{ title: "Dune", read: false }],
    content: "In the week before their departure to Arrakis, when all the final scurrying about had reached a nearly unbearable frenzy, an old crone came to visit the mother of the boy, Paul.",
  },
];

export function getBooks(): Book[] {
  return mockBooks;
}

export function getBookBySlug(slug: string): Book | undefined {
  return mockBooks.find((book) => book.slug === slug);
}
